<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net48;net8.0-windows</TargetFrameworks>
    <UseWindowsForms>true</UseWindowsForms>
    <OutputType>Library</OutputType>
    <RootNamespace>IndustrialCameraManager</RootNamespace>
    <AssemblyName>IndustrialCameraManager</AssemblyName>
    <LangVersion>13</LangVersion>
  </PropertyGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net48'">
    <PackageReference Include="Microsoft.Bcl.AsyncInterfaces" />
    <PackageReference Include="System.Drawing.Common" />
    <PackageReference Include="System.Runtime.CompilerServices.Unsafe" />
    <PackageReference Include="System.Threading.Channels" />
    <PackageReference Include="System.Threading.Tasks.Extensions" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="MvCameraControl.Net">
      <SpecificVersion>False</SpecificVersion>
      <HintPath>..\..\DLL\MvCameraControl.Net.dll</HintPath>
    </Reference>
    <Reference Include="MVSDK_Net">
      <HintPath>..\..\..\..\..\iCloud\iCloudDrive\WorkSpace\MachineVision\IRayple\Industrial Camera\Dll\MVSDK_Net.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
